//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAlfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codigos()
        {
            this.libroscodigos = new HashSet<libroscodigos>();
        }
    
        public long Id { get; set; }
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public string Activo { get; set; }
        public int TotalLibros { get; set; }
        public Nullable<int> CantidadRestante { get; set; }
        public string UUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libroscodigos> libroscodigos { get; set; }
    }
}
