//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAlfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class libroscodigos
    {
        public long Id { get; set; }
        public long CodigoId { get; set; }
        public Nullable<long> LibroId { get; set; }
        public string UUID { get; set; }
        public string Activo { get; set; }
    
        public virtual codigos codigos { get; set; }
        public virtual libros libros { get; set; }
    }
}
