//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAlfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libros()
        {
            this.libroscodigos = new HashSet<libroscodigos>();
            this.libroscategorias = new HashSet<libroscategorias>();
            this.versiones = new HashSet<versiones>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> NumeroPaginas { get; set; }
        public Nullable<int> AnoEdicion { get; set; }
        public string Grado { get; set; }
        public Nullable<long> EspecialidadId { get; set; }
        public string Ruta { get; set; }
        public string RutaThumbnails { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Resena { get; set; }
        public string tags { get; set; }
        public string RutaImgResena { get; set; }
        public Nullable<sbyte> Version { get; set; }
    
        public virtual especialidades especialidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libroscodigos> libroscodigos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libroscategorias> libroscategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<versiones> versiones { get; set; }
    }
}
