//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAlfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class libroscategorias
    {
        public long Id { get; set; }
        public long LibroId { get; set; }
        public long CategoriaId { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual libros libros { get; set; }
    }
}
