//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAlfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class versiones
    {
        public long Id { get; set; }
        public Nullable<long> LibroId { get; set; }
        public Nullable<sbyte> Version { get; set; }
        public string NombreArchivo { get; set; }
    
        public virtual libros libros { get; set; }
    }
}
